// Command geninv writes a big fake inventory for scale tests, so that no
// file with thousands of lines is committed to the repo.
//
//	geninv -n 5000 -inventory /tmp/inv.toml -nodes /tmp/nodes.txt
//	geninv -n 5000 -inventory /tmp/inv.toml -nodes /tmp/nodes.txt -viewers /tmp/viewers.toml
//
// With -viewers, the machines that are not guests get no port; the file it
// writes gives each program a default_port (the fake port), so a run uses the
// default ports. Guests keep their own port (a guest has no default).
//
// Machine addresses are 127.1.x.y on port 21000 (fake: no real port is
// meant). nodes.txt lists the host:port of every machine that should be UP,
// one per line, ready for `xargs fakenode`; every -down-every'th machine is
// left out of it so it shows as DOWN. This is a test helper, never part of
// the Hub OS image.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
)

func main() {
	n := flag.Int("n", 100, "number of machines besides the hub")
	invPath := flag.String("inventory", "", "where to write the inventory (required)")
	nodesPath := flag.String("nodes", "", "where to write the host:port list of UP machines (required)")
	downEvery := flag.Int("down-every", 20, "every k-th machine is left DOWN (0 = none)")
	port := flag.Int("port", 21000, "the fake port of every machine")
	viewersPath := flag.String("viewers", "", "write a viewers.toml here with default_port for moonlight, files and ssh, and leave the port out of every machine except guests")
	unreachable := flag.Bool("unreachable", false, "use 192.0.2.x addresses that nothing answers (checks time out) and list no nodes")
	flag.Parse()
	if *invPath == "" || *nodesPath == "" || *n < 1 {
		fmt.Fprintln(os.Stderr, "usage: geninv -n N -inventory FILE -nodes FILE [-down-every K] [-port P]")
		os.Exit(1)
	}
	if err := generate(*n, *downEvery, *port, *unreachable, *invPath, *nodesPath, *viewersPath); err != nil {
		fmt.Fprintln(os.Stderr, "geninv:", err)
		os.Exit(1)
	}
}

type spec struct{ id, name, role, open, extra string }

func plan(n int) []spec {
	hosts := n / 50
	if hosts < 1 {
		hosts = 1
	}
	var out []spec
	add := func(role, open, prefix string, count int) {
		for i := 1; i <= count; i++ {
			id := fmt.Sprintf("%s-%d", prefix, i)
			out = append(out, spec{id, fmt.Sprintf("%s %d", prefix, i), role, open, ""})
		}
	}
	add("gaming", "moonlight", "gaming", 1)
	add("ai", "moonlight", "ai", n/20)
	add("desktop", "moonlight", "desktop", n/10)
	add("nas", "files", "nas", n/33)
	add("backup-nas", "files", "backup", n/100)
	add("vm-host", "ssh", "vmhost", hosts)
	for i := 1; len(out) < n; i++ {
		host := fmt.Sprintf("vmhost-%d", (i-1)%hosts+1)
		out = append(out, spec{fmt.Sprintf("guest-%d", i), fmt.Sprintf("Guest %d", i), "guest", "vnc",
			fmt.Sprintf("host = %q\nlifetime = \"ephemeral\"\n", host)})
	}
	return out[:n]
}

func generate(n, downEvery, port int, unreachable bool, invPath, nodesPath, viewersPath string) error {
	inv, err := os.Create(invPath)
	if err != nil {
		return err
	}
	defer inv.Close()
	nodes, err := os.Create(nodesPath)
	if err != nil {
		return err
	}
	defer nodes.Close()
	iw, nw := bufio.NewWriter(inv), bufio.NewWriter(nodes)
	fmt.Fprintf(iw, "# Generated by tools/geninv. Fake. Not committed.\nformat = 1\n\n")
	fmt.Fprintf(iw, "[[machine]]\nid = \"hub\"\nname = \"Hub\"\nrole = \"hub\"\naddress = \"127.0.0.10\"\nopen = [\"none\"]\nhome = { x = -300, y = -300 }\n\n")
	for i, s := range plan(n) {
		addr := fmt.Sprintf("127.1.%d.%d", i/250, i%250+1)
		mport := port
		if unreachable {
			// 192.0.2.0/24 is reserved for documentation; nothing answers, so
			// every check runs into its time limit. Ports differ so that
			// every machine still has its own address and port pair.
			addr, mport = fmt.Sprintf("192.0.2.%d", i%250+1), port+i/250
		}
		portLine := fmt.Sprintf("port = %d\n", mport)
		if viewersPath != "" && s.role != "guest" {
			portLine = "" // the viewer's default_port is used
		}
		fmt.Fprintf(iw, "[[machine]]\nid = %q\nname = %q\nrole = %q\naddress = %q\nopen = [%q]\n%shome = { x = %d, y = %d }\n%s\n",
			s.id, s.name, s.role, addr, s.open, portLine, (i%100)*300, (i/100)*300, s.extra)
		if !unreachable && (downEvery == 0 || (i+1)%downEvery != 0) {
			fmt.Fprintf(nw, "%s:%d\n", addr, mport)
		}
	}
	if err := iw.Flush(); err != nil {
		return err
	}
	if viewersPath != "" {
		doc := "# Generated by tools/geninv. Fake. Not committed.\nformat = 1\n"
		for _, p := range []string{"moonlight", "files", "ssh"} {
			doc += fmt.Sprintf("\n[[viewer]]\nid = %q\nprograms = [%q]\ncommand = [\"foot\", \"--app-id={app_id}\", \"--\", \"sleep\", \"infinity\"]\nsets_name = true\ndefault_port = %d\n", p, p, port)
		}
		// vnc (the guests) has no default: the inventory gives the port.
		doc += "\n[[viewer]]\nid = \"vnc\"\nprograms = [\"vnc\"]\ncommand = [\"foot\", \"--app-id={app_id}\", \"--\", \"sleep\", \"infinity\"]\nsets_name = true\n"
		if err := os.WriteFile(viewersPath, []byte(doc), 0o600); err != nil {
			return err
		}
	}
	return nw.Flush()
}
