#!/usr/bin/env python3
"""Turns results/raw/*.txt into results/summary.md (min / median / max over the runs of each cell, N shown).
usage: summarize.py [RAW_DIR] [OUT_MD]
Standard library only. Cells are keyed by (stack, client, scene, res); every raw file is one run."""
import glob, os, re, statistics, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "results", "raw")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "results", "summary.md")


def load(p):
    d = {}
    for ln in open(p, encoding="utf-8", errors="replace"):
        if "=" in ln:
            k, v = ln.rstrip("\n").split("=", 1)
            d[k] = v
    return d


runs = {}   # (stack, client, scene, res) -> [dict]
scale = []
for p in sorted(glob.glob(os.path.join(RAW, "*.txt"))):
    d = load(p)
    if os.path.basename(p).startswith("scale__"):
        scale.append(d)
        continue
    key = (d.get("stack"), d.get("client"), d.get("scene"), d.get("res"))
    runs.setdefault(key, []).append(d)

SHORT = {"1280x720": "720p", "1920x1080": "1080p", "3840x2160": "4k"}


def num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def mmm(vals, fmt="%.1f"):
    v = [x for x in vals if x is not None]
    if not v:
        return "n/a"
    return (fmt + " / " + fmt + " / " + fmt) % (min(v), statistics.median(v), max(v))


def okruns(cell):
    return [r for r in cell if r.get("status") == "ok"]


def first3(s):
    p = (s or "").split()
    return [num(x) for x in p[:3]] if len(p) >= 3 else []


def cell_rows(scene, res):
    for key in sorted(runs):
        if key[2] == scene and SHORT.get(key[3], key[3]) == res:
            yield key, runs[key]


def table(title, scene, res, cols, note=""):
    """cols: list of (header, function(run)->float|None, fmt)"""
    rows = []
    for (st, cl, sc, rs), cell in cell_rows(scene, res):
        ok = okruns(cell)
        if not ok:
            why = cell[0].get("status", "?")
            rows.append("| %s | %s | 0/%d | %s |" % (st, cl, len(cell), why.replace("|", "/")) + " |" * (len(cols) - 1))
            continue
        vals = [mmm([f(r) for r in ok], fm) for _, f, fm in cols]
        rows.append("| %s | %s | %d | %s |" % (st, cl, len(ok), " | ".join(vals)))
    if not rows:
        return ""
    head = "| stack | client | N | " + " | ".join(h for h, _, _ in cols) + " |\n|---|---|---|" + "---|" * len(cols)
    return "### %s\n\n%s\n\n%s\n%s\n\n" % (title, note, head, "\n".join(rows))


def g(k):
    return lambda r: num(r.get(k))


def total(prefix, groups, suffix):
    def f(r):
        vals = [num(r.get("%s_%s_%s" % (prefix, grp, suffix))) for grp in groups]
        return sum(v for v in vals if v is not None) if any(v is not None for v in vals) else None
    return f


NODE = ("node_srv", "node_comp", "node_app")
NODE_NOAPP = ("node_srv", "node_comp")
HUB = ("hub_viewer", "hub_comp")
out = ["# Remote display benchmark: summary of the raw results\n\nGenerated by `summarize.py` from `results/raw/*.txt`. Cells show **min / median / max** over N runs. CPU is percent of ONE core (4 cores = 400). \"node\" = server + compositor + test program; \"node w/o app\" leaves the test program out (what the remote display costs); \"hub\" = viewer + hub compositor. `kbit/s` is server to client, measured on the socket.\n"]
# the short table: medians at 1080p, one row per stack and viewer
def med_of(st, cl, scene, res, f):
    cell = runs.get((st, cl, scene, res), [])
    v = [f(r) for r in okruns(cell)]
    v = [x for x in v if x is not None]
    return statistics.median(v) if v else None
def cell(x, fm):
    return "n/a" if x is None else fm % x
def fidv(r, key, which):
    m = re.search(which + r"=([0-9.]+|inf)", r.get(key, ""))
    return float(m.group(1)) if m else None
CLIP = {}
for key, cellruns in runs.items():
    if key[2] == "clipboard" and key[3] == "1920x1080":
        r = okruns(cellruns)[0] if okruns(cellruns) else {}
        n2h, h2n = r.get("clip_node_to_hub_utf8_exact") == "yes" and r.get("clip_node_to_hub_ascii_exact") == "yes", r.get("clip_hub_to_node_utf8_exact") == "yes" and r.get("clip_hub_to_node_ascii_exact") == "yes"
        n2h_a, h2n_a = r.get("clip_node_to_hub_ascii_exact") == "yes", r.get("clip_hub_to_node_ascii_exact") == "yes"
        CLIP[(key[0], key[1])] = "both ways, UTF-8 ok" if n2h and h2n else ("node to hub, UTF-8 ok" if n2h and not h2n_a else ("node to hub, ASCII only (UTF-8 garbled)" if n2h_a and not h2n_a else ("none" if not n2h_a and not h2n_a else "partial")))
rows = []
for (st, cl) in sorted(set((k[0], k[1]) for k in runs if k[3] == "1920x1080" and k[2] == "scroll")):
    R = "1920x1080"
    rows.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (st, cl,
        cell(med_of(st, cl, "scroll", R, lambda r: num(r.get("m_s2c_kbit_s"))), "%.0f"),
        cell(med_of(st, cl, "scroll", R, total("m", HUB, "cpu")), "%.0f"),
        cell(med_of(st, cl, "video", R, lambda r: num(r.get("video_dropped_pct"))), "%.1f"),
        cell(med_of(st, cl, "latency", R, lambda r: (first3(r.get("input_to_pixel_ms_min_med_max")) or [None, None])[1]), "%.0f"),
        cell(med_of(st, cl, "latency", R, lambda r: num(r.get("time_to_first_frame_ms"))), "%.0f"),
        "%s / %s" % (cell(med_of(st, cl, "fidelity", R, lambda r: fidv(r, "fidelity_full", "ssim")), "%.4f"), cell(med_of(st, cl, "fidelity", R, lambda r: fidv(r, "fidelity_full", "psnr")), "%.1f")),
        CLIP.get((st, cl), "n/a")))
out.append("### short table, 1080p, medians\n\nOne row per stack and viewer; every number is the median of N = 3 runs (clipboard: one run) taken from the longer tables below. \"hub CPU\" is the hub's viewer plus the hub compositor in the scrolling-text scene (100 = one full core). Cage is left out (720p only).\n\n| stack | viewer | scrolling text kbit/s | hub CPU %% (scroll) | video frames dropped %% | click to pixel ms | first frame ms | text SSIM / PSNR dB | clipboard |\n|---|---|---|---|---|---|---|---|---|\n".replace("%%", "%") + "\n".join(rows) + "\n\n")

for res in ("1080p", "720p", "4k"):
    for scene in ("idle", "scroll", "term", "drag", "video"):
        out.append(table("%s, %s" % (scene, res), scene, res, [
            ("kbit/s", g("m_s2c_kbit_s"), "%.0f"),
            ("node CPU %", total("m", NODE, "cpu"), "%.0f"),
            ("node w/o app CPU %", total("m", NODE_NOAPP, "cpu"), "%.0f"),
            ("hub CPU %", total("m", HUB, "cpu"), "%.0f"),
            ("node RSS MB", total("m", NODE, "rss_mb"), "%.0f"),
            ("hub RSS MB", total("m", HUB, "rss_mb"), "%.0f"),
        ]))
    out.append(table("latency: time to first frame and input-to-pixel, %s" % res, "latency", res, [
        ("first frame ms", g("time_to_first_frame_ms"), "%.0f"),
        ("click to node ms", lambda r: (first3(r.get("input_to_node_ms_min_med_max")) or [None, None])[1], "%.1f"),
        ("input to pixel ms (median of 20 clicks)", lambda r: (first3(r.get("input_to_pixel_ms_min_med_max")) or [None, None])[1], "%.1f"),
        ("input to pixel ms (worst click)", lambda r: (first3(r.get("input_to_pixel_ms_min_med_max")) or [None, None, None])[2], "%.1f"),
    ], "Resolution of the pixel watcher: one hub frame, 16.7 ms."))
    out.append(table("video: dropped frames, %s" % res, "video", res, [
        ("shown fps (of 30)", g("video_shown_fps"), "%.1f"),
        ("dropped frames %", g("video_dropped_pct"), "%.1f"),
    ]))
    def fid(key, which):
        def f(r):
            m = re.search(which + r"=([0-9.]+|inf)", r.get(key, ""))
            return float(m.group(1)) if m else None
        return f
    out.append(table("text fidelity, %s" % res, "fidelity", res, [
        ("SSIM whole screen", fid("fidelity_full", "ssim"), "%.4f"),
        ("PSNR whole dB", fid("fidelity_full", "psnr"), "%.1f"),
        ("SSIM text area", fid("fidelity_textarea", "ssim"), "%.4f"),
        ("PSNR text area dB", fid("fidelity_textarea", "psnr"), "%.1f"),
    ], "SSIM and PSNR of a screenshot of the hub against the node's own screenshot (tools/bench/remote-display/ssim). 1.0 and inf mean identical pictures."))

# one-line-per-run tables for the behaviour scenes
def lines(title, scene, keys):
    rows = []
    for key in sorted(runs):
        if key[2] != scene:
            continue
        for r in runs[key]:
            vals = [r.get(k, "") for k in keys]
            rows.append("| %s | %s | %s | %s | %s |" % (key[0], key[1], SHORT.get(key[3], key[3]), r.get("run"), r.get("status") if r.get("status") != "ok" else "ok") + "".join(" %s |" % v.replace("|", "/") for v in vals))
    if not rows:
        return ""
    return "### %s\n\n| stack | client | res | run | status |%s\n|---|---|---|---|---|%s\n%s\n\n" % (title, "".join(" %s |" % k for k in keys), "---|" * len(keys), "\n".join(rows))

out.append(lines("clipboard text, both ways (exact = the receiving side got precisely the text that was copied)", "clipboard", ["clip_node_to_hub_ascii_exact", "clip_node_to_hub_utf8_exact", "clip_hub_to_node_ascii_exact", "clip_hub_to_node_utf8_exact", "clip_node_to_hub_utf8"]))
out.append(lines("reconnect", "reconnect", ["reconnect_new_viewer_ms", "link_cut_viewer_alive_after_15s", "link_cut_new_connections_in_15s", "link_cut_picture_back_ms"]))
out.append(lines("does the server go quiet when the viewer stops asking (frozen viewer)", "quiet", ["running_s2c_kbit_s", "frozen_s2c_kbit_s", "resumed_s2c_kbit_s", "running_node_srv_cpu", "frozen_node_srv_cpu", "running_node_comp_cpu", "frozen_node_comp_cpu", "running_node_app_cpu", "frozen_node_app_cpu"]))
out.append(lines("the viewer is asked to become smaller", "smallsize", ["node_size_before", "node_size_after", "hub_window_before", "hub_window_after", "viewer_alive_after", "hub_window_screenshot"]))
out.append(lines("the node changes its own screen size", "resize", ["resize_down_s2c_bytes", "resize_viewer_alive_after_down", "resize_up_s2c_bytes", "resize_after_ssim", "resize_viewer_alive_end"]))
enc = {}
for key in sorted(runs):
    for r in runs[key]:
        v = r.get("client_encodings")
        if v and r.get("status") == "ok":
            enc.setdefault((key[0], key[1]), set()).add(v)
rows = ["| %s | %s | %s |" % (st, cl, " / ".join(sorted(vs)) if len(vs) == 1 else " **(differs between runs)** " + " / ".join(sorted(vs))) for (st, cl), vs in sorted(enc.items())]
if rows:
    out.append("### encodings the VNC viewers asked for (in the order sent; plain connections only)\n\n| stack | client | encodings |\n|---|---|---|\n" + "\n".join(rows) + "\n\nNumbers are encodings this table does not know the name of. Weston's VNC backend uses TLS from the start, so the list cannot be read there.\n\n")

if scale:
    groups = {}
    for d in scale:
        groups.setdefault((d.get("stack"), d.get("client"), d.get("sessions")), []).append(d)
    def drop(d):
        a, b = num(d.get("free_mem_before_mb")), num(d.get("free_mem_with_all_mb"))
        return a - b if a is not None and b is not None else None
    base = [drop(d) for (st, cl, n), ds in groups.items() if cl == "none" for d in ds if d.get("status") == "ok"]
    base = [x for x in base if x is not None]
    base_med = statistics.median(base) if base else None
    out.append("### scale test: 20 sessions (20 nodes) into one hub\n\nMemory is PSS (shared libraries counted once) of the processes named; it can miss memory that the hub's Xwayland or compositor keeps in shared buffers, so the last column gives the whole machine's view: how much `MemAvailable` fell with 20 nodes and 20 viewers, minus how much it fell with the 20 nodes alone (%s MB, median of %d runs). \"alive\" = viewers still running when the measurement started. CPU is percent of one core. min / median / max over the runs.\n\n| stack | client | sessions | N | alive | phase | hub viewers CPU %% | hub compositor CPU %% | hub viewers PSS MB | hub compositor PSS MB | all 20 nodes CPU %% | all 20 nodes PSS MB | hub side, whole-machine MB |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n" % ("%.0f" % base_med if base_med is not None else "?", len(base)))
    for (st, cl, n), ds in sorted(groups.items()):
        ok = [d for d in ds if d.get("status") == "ok"]
        if cl == "none":
            continue
        for ph in ("idle", "one_busy"):
            def col(k, fm="%.1f"):
                return mmm([num(d.get(ph + "_" + k)) for d in ok], fm)
            hubmem = mmm([(drop(d) - base_med) if drop(d) is not None and base_med is not None else None for d in ok], "%.0f") if ph == "idle" else "(same machine state)"
            out.append("| %s | %s | %s | %d | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n" % (st, cl, n, len(ok), "/".join(d.get("viewers_alive", "?") for d in ok), "20 idle" if ph == "idle" else "19 idle + 1 busy (30 lines/s)",
                       col("hub_viewers_cpu"), col("hub_comp_cpu"), col("hub_viewers_pss_mb", "%.0f"), col("hub_comp_pss_mb", "%.0f"), col("all_nodes_cpu"), col("all_nodes_pss_mb", "%.0f"), hubmem))
    out.append("\n")

# loads
out.append("### machine load at the start of each run (uptime 1/5/15 min), for the record\n\n")
loads = sorted(set((k[0], k[1], k[2], SHORT.get(k[3], k[3]), r.get("load_start", "")) for k, c in runs.items() for r in c))
out.append("Range of the 1-minute load average at the start of runs: %s\n" % mmm([num((x[4].split() or [None])[0]) for x in loads], "%.2f"))
open(OUT, "w").write("".join(out))
print("wrote", OUT)
